name: Build Twinstagram-gui

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Use Node'
      uses: actions/setup-node@v1
      with: 
        node-version: 14.16.*
    - name: 'Install'
      run: npm i
    - name: 'Build'
      run: npm run build
    - name: 'Run'
      run: npm start